syntax = "proto3";
package querier.v1;

import "types/v1/types.proto";

service QuerierService {
  rpc Series(SeriesRequest) returns (SeriesResponse);
  rpc SelectMergeStacktraces(SelectMergeStacktracesRequest) returns (SelectMergeStacktracesResponse);
  rpc SelectSeries(SelectSeriesRequest) returns (SelectSeriesResponse);
  rpc SelectHeatmap(SelectHeatmapRequest) returns (SelectHeatmapResponse);
}

message SeriesRequest {
  repeated string matchers = 1;
  repeated string label_names = 2;
  int64 start = 3;
  int64 end = 4;
}

message SeriesResponse {
  // field number 2 matches the upstream proto
  repeated types.v1.Labels labels_set = 2;
}

message SelectMergeStacktracesRequest {
  // Profile Type ID string: <name>:<type>:<unit>:<period_type>:<period_unit>
  string profile_typeID = 1;
  string label_selector = 2;
  int64 start = 3;
  int64 end = 4;
  optional int64 max_nodes = 5;
  ProfileFormat format = 6;
}

enum ProfileFormat {
  PROFILE_FORMAT_UNSPECIFIED = 0;
  PROFILE_FORMAT_FLAMEGRAPH = 1;
  PROFILE_FORMAT_TREE = 2;
}

message SelectMergeStacktracesResponse {
  FlameGraph flamegraph = 1;
}

message FlameGraph {
  repeated string names = 1;
  repeated Level levels = 2;
  int64 total = 3;
  int64 max_self = 4;
}

message Level {
  repeated int64 values = 1;
}

message SelectSeriesRequest {
  string profile_typeID = 1;
  string label_selector = 2;
  int64 start = 3;
  int64 end = 4;
  repeated string group_by = 5;
  double step = 6;
  optional types.v1.TimeSeriesAggregationType aggregation = 7;
}

message SelectSeriesResponse {
  repeated types.v1.Series series = 1;
}

enum HeatmapQueryType {
  HEATMAP_QUERY_TYPE_UNSPECIFIED = 0;
  HEATMAP_QUERY_TYPE_INDIVIDUAL = 1;
  HEATMAP_QUERY_TYPE_SPAN = 2;
}

message SelectHeatmapRequest {
  string profile_typeID = 1;
  string label_selector = 2;
  int64 start = 3;
  int64 end = 4;
  double step = 5;
  repeated string group_by = 6;
  HeatmapQueryType query_type = 7;
}

message SelectHeatmapResponse {
  repeated types.v1.HeatmapSeries series = 1;
}
