syntax = "proto3";

package querier.v1;

import "types/v1/types.proto";

service QuerierService {
  rpc ProfileTypes(ProfileTypesRequest) returns (ProfileTypesResponse);
  rpc LabelValues(types.v1.LabelValuesRequest) returns (types.v1.LabelValuesResponse);
  rpc LabelNames(types.v1.LabelNamesRequest) returns (types.v1.LabelNamesResponse);
  rpc Series(SeriesRequest) returns (SeriesResponse);
  rpc SelectMergeStacktraces(SelectMergeStacktracesRequest) returns (SelectMergeStacktracesResponse);
  rpc SelectMergeSpanProfile(SelectMergeSpanProfileRequest) returns (SelectMergeSpanProfileResponse);
  rpc SelectSeries(SelectSeriesRequest) returns (SelectSeriesResponse);
  rpc SelectHeatmap(SelectHeatmapRequest) returns (SelectHeatmapResponse);
  rpc Diff(DiffRequest) returns (DiffResponse);
  rpc GetProfileStats(types.v1.GetProfileStatsRequest) returns (types.v1.GetProfileStatsResponse);
  rpc AnalyzeQuery(AnalyzeQueryRequest) returns (AnalyzeQueryResponse);
}

message ProfileTypesRequest {
  int64 start = 1;
  int64 end = 2;
}

message ProfileTypesResponse {
  repeated types.v1.ProfileType profile_types = 1;
}

message SeriesRequest {
  repeated string matchers = 1;
  repeated string label_names = 2;
  int64 start = 3;
  int64 end = 4;
}

message SeriesResponse {
  repeated types.v1.Labels labels_set = 2;
}

message SelectMergeStacktracesRequest {
  string profile_typeID = 1;
  string label_selector = 2;
  int64 start = 3;
  int64 end = 4;
  optional int64 max_nodes = 5;
  ProfileFormat format = 6;
  optional types.v1.StackTraceSelector stack_trace_selector = 7;
  repeated string profile_id_selector = 8;
}

enum ProfileFormat {
  PROFILE_FORMAT_UNSPECIFIED = 0;
  PROFILE_FORMAT_FLAMEGRAPH = 1;
  PROFILE_FORMAT_TREE = 2;
}

message SelectMergeStacktracesResponse {
  FlameGraph flamegraph = 1;
  bytes tree = 2;
}

message SelectMergeSpanProfileRequest {
  string profile_typeID = 1;
  string label_selector = 2;
  repeated string span_selector = 3;
  int64 start = 4;
  int64 end = 5;
  optional int64 max_nodes = 6;
  ProfileFormat format = 7;
}

message SelectMergeSpanProfileResponse {
  FlameGraph flamegraph = 1;
  bytes tree = 2;
}

message DiffRequest {
  SelectMergeStacktracesRequest left = 1;
  SelectMergeStacktracesRequest right = 2;
}

message DiffResponse {
  FlameGraphDiff flamegraph = 1;
}

message FlameGraph {
  repeated string names = 1;
  repeated Level levels = 2;
  int64 total = 3;
  int64 max_self = 4;
}

message FlameGraphDiff {
  repeated string names = 1;
  repeated Level levels = 2;
  int64 total = 3;
  int64 max_self = 4;
  int64 leftTicks = 5;
  int64 rightTicks = 6;
}

message Level {
  repeated int64 values = 1;
}

message SelectSeriesRequest {
  string profile_typeID = 1;
  string label_selector = 2;
  int64 start = 3;
  int64 end = 4;
  repeated string group_by = 5;
  double step = 6;
  optional types.v1.TimeSeriesAggregationType aggregation = 7;
  optional types.v1.StackTraceSelector stack_trace_selector = 8;
  optional int64 limit = 9;
  types.v1.ExemplarType exemplar_type = 10;
}

message SelectSeriesResponse {
  repeated types.v1.Series series = 1;
}

enum HeatmapQueryType {
  HEATMAP_QUERY_TYPE_UNSPECIFIED = 0;
  HEATMAP_QUERY_TYPE_INDIVIDUAL = 1;
  HEATMAP_QUERY_TYPE_SPAN = 2;
}

message SelectHeatmapRequest {
  string profile_typeID = 1;
  string label_selector = 2;
  int64 start = 3;
  int64 end = 4;
  double step = 5;
  repeated string group_by = 6;
  HeatmapQueryType query_type = 7;
  types.v1.ExemplarType exemplar_type = 8;
  optional int64 limit = 9;
}

message SelectHeatmapResponse {
  repeated types.v1.HeatmapSeries series = 1;
}

message AnalyzeQueryRequest {
  int64 start = 2;
  int64 end = 3;
  string query = 4;
}

message AnalyzeQueryResponse {
  repeated QueryScope query_scopes = 1;
  QueryImpact query_impact = 2;
}

message QueryScope {
  string component_type = 1;
  uint64 component_count = 2;
  uint64 block_count = 3;
  uint64 series_count = 4;
  uint64 profile_count = 5;
  uint64 sample_count = 6;
  uint64 index_bytes = 7;
  uint64 profile_bytes = 8;
  uint64 symbol_bytes = 9;
}

message QueryImpact {
  uint64 total_bytes_in_time_range = 2;
  uint64 total_queried_series = 3;
  bool deduplication_needed = 4;
}
