name: zizmor

on:
  pull_request:
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run nixpkgs#zizmor -- --format sarif .github/workflows/ > zizmor.sarif
      - uses: github/codeql-action/upload-sarif@ce64ddcb0d8d890d2df4a9d1c04ff297367dea2a # v3
        if: always()
        with:
          sarif_file: zizmor.sarif
          category: zizmor
